Repository XFox111/SimpleOTP, pull requests merged in 2021-06, with the labels that each got.

#15 Worked on issue #14
  README.md
  SimpleOTP/Models/OTPCode.cs
  SimpleOTP/Models/OTPConfiguration.cs
Labels: documentation, good first issue

#16 Version 1.2.0
  README.md
  SimpleOTP/Models/OTPCode.cs
  SimpleOTP/Models/OTPConfiguration.cs
  SimpleOTP/SimpleOTP.csproj
Labels: documentation, enhancement

#18 Secret generator & URI encoder fixes
  SimpleOTP.Test/Models/OTPConfigurationUnitTest.cs
  SimpleOTP/Helpers/SecretGenerator.cs
  SimpleOTP/Models/OTPCode.cs
  SimpleOTP/Models/OTPConfiguration.cs
  SimpleOTP/SimpleOTP.csproj
Labels: bug
